### ISSUE TITLE
Error "useRouter is not defined"

### ISSUE THREAD

**Issue by henriksjodahl** [YsarocK/nuxt-query-sync#1]
Hi! I've just installed the package but are getting "useRouter is not defined" error from `usePersistence`

```
<script setup lang="ts">
const page = ref(1)
usePersistence(page, 'page')

function next() {
  page.value += 1
}
</script>

<template>
  <div>
    {{ page }}
    <NuxtLink @click="next">Open next page</NuxtLink>
  </div>
</template>
```

**Comment by YsarocK** [comment]
Hi @henriksjodahl !

Sorry for the inconvenience, failed my imports. It is now fixed in 1.0.5, just released it.

Thanks a lot!
